name: Release new version of the module to the Puppet Forge

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Build and publish module
        uses: barnumbirr/action-forge-publish@v2.8.0
        env:
          FORGE_API_KEY: ${{ secrets.FORGE_API_KEY }}
          REPOSITORY_URL: https://forgeapi.puppet.com/v3/releases
